WebApplication1/Controllers/Admin_Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class Admin_Controller : Controller
    {
        pioneer db = new pioneer();
        private bool auth_display_user(int id)
        {
            if (id != 0)
            {
                Admin aa1 = db.Admins.Where(m => m.id_admin == id).FirstOrDefault();
                List<page> pp1 = db.pages.Where(m => m.id_group == aa1.id_group && m.name == "Users_Admin").ToList();
                foreach (var item in pp1)
                {
                    if (item.show == true)
                    {
                        return true;
                    }
                }
                return false;

            }
            else
                return false;
        }
        private bool auth_add_user(int id)
        {
            if (id != 0)
            {
                Admin aa1 = db.Admins.Where(m => m.id_admin == id).FirstOrDefault();
                List<page> pp1 = db.pages.Where(m => m.id_group == aa1.id_group && m.name == "Users_Admin").ToList();
                foreach (var item in pp1)
                {
                    if (item.insert == true)
                    {
                        return true;
                    }
                }
                return false;

            }
            else
                return false;
        }
        private bool auth_update_user(int id)
        {
            if (id != 0)
            {
                Admin aa1 = db.Admins.Where(m => m.id_admin == id).FirstOrDefault();
                List<page> pp1 = db.pages.Where(m => m.id_group == aa1.id_group && m.name == "Users_Admin").ToList();
                foreach (var item in pp1)
                {
                    if (item.update == true)
                    {
                        return true;
                    }
                }
                return false;

            }
            else
                return false;
        }
        private bool auth_delete_user(int id)
        {
            if (id != 0)
            {
                Admin aa1 = db.Admins.Where(m => m.id_admin == id).FirstOrDefault();
                List<page> pp1 = db.pages.Where(m => m.id_group == aa1.id_group && m.name == "Users_Admin").ToList();
                foreach (var item in pp1)
                {
                    if (item.delete == true)
                    {
                        return true;
                    }
                }
                return false;

            }
            else
                return false;
        }


        public ActionResult View_users()
        {

            if (Session["HR_id"] != null || Session["admin_id"] != null)
            {
                int admin_id = 0;
                if (Session["admin_id"] != null)
                    admin_id = (int)Session["admin_id"];


                bool auth = auth_display_user(admin_id);
                if (auth==true || Session["HR_id"] != null)
                {
                    List<Admin> admin_to_display = db.Admins.ToList();

                    return View(admin_to_display);
                }
                else
                {
                    TempData["Message"] = "un authorize to enter this page ";

                    return Redirect(Request.UrlReferrer.ToString());
                }
            }
            else
            {
                return RedirectToAction("login", "HR");
            }
            
        }
        // GET: Admin
        public ActionResult add_new_user()
        {
            if (Session["HR_id"] != null || Session["admin_id"] != null)
            {
                int admin_id = 0;
                if (Session["admin_id"] != null)
                    admin_id = (int)Session["admin_id"];
 
                bool auth = auth_add_user(admin_id);
                if (auth==true || Session["HR_id"] != null)
                {
                    Admin adding_Admin = new Admin();
                    SelectList st = new SelectList(db.Group.ToList(), "id_group", "name_group");
                    ViewBag.cat = st;


                    return View(adding_Admin);
                }
                else
                {
                    TempData["Message"] = "un authorize to enter this page ";

                    return Redirect(Request.UrlReferrer.ToString());
                }
            }
            else
            {
                return RedirectToAction("login", "HR");
            }
        }

        [HttpPost]
        public ActionResult add_new_user(Admin adding1)
        {
            if (ModelState.IsValid)
            {

                db.Admins.Add(adding1);
                db.SaveChanges();
                return RedirectToAction("View_users");
            }
            return RedirectToAction("home","HR");

        }

        public ActionResult Edit_admin(int id )
        {
            if (Session["HR_id"] != null || Session["admin_id"] != null)
            {
                int admin_id = 0;
                if (Session["admin_id"] != null)
                    admin_id = (int)Session["admin_id"];


                bool auth = auth_update_user(admin_id);
                if (auth==true || Session["HR_id"] != null)
                {
                    Admin admin_edit = db.Admins.Where(m => m.id_admin == id).FirstOrDefault();
                    SelectList st = new SelectList(db.Group.ToList(), "id_group", "name_group");
                    ViewBag.cat = st;

                    return View(admin_edit);
                }
                else
                {
                    TempData["Message"] = "un authorize to enter this page ";

                    return Redirect(Request.UrlReferrer.ToString());
                }
            }
            else
            {
                return RedirectToAction("login", "HR");
            }

           
        }
        [HttpPost]
        public ActionResult Edit_admin(Admin update_admin)
        {
            if (ModelState.IsValid)
            {
                db.Entry(update_admin).State = System.Data.Entity.EntityState.Modified;

                db.SaveChanges();

                return RedirectToAction("View_users");

            }
            return View();
        }
        public ActionResult Delete_admin(int id)
        {
            if (Session["HR_id"] != null || Session["admin_id"] != null)
            {
                int admin_id = 0;
                if (Session["admin_id"] != null)
                    admin_id = (int)Session["admin_id"];


                bool auth = auth_delete_user(admin_id);
                if (auth==true || Session["HR_id"] != null)
                {
                    if (id != 0)
                    {
                        Admin admin_delete = db.Admins.Where(m => m.id_admin == id).FirstOrDefault();
                        db.Admins.Remove(admin_delete);
                        db.SaveChanges();

                        return RedirectToAction("View_users");
                    }
                    else
                    {
                        return RedirectToAction("home", "HR");
                    }
                }
                else
                {
                    TempData["Message"] = "un authorize to enter this page ";

                    return Redirect(Request.UrlReferrer.ToString());
                }
            }
            else
            {
                return RedirectToAction("login", "HR");
            }
            
        }


    }
    }

WebApplication1/Views/Admin_/Edit_admin.cshtml
@model WebApplication1.Models.Admin

@{
    ViewBag.Title = "Edit_admin";
    Layout = "~/Views/Shared/_Layout_system.cshtml";
}


<!DOCTYPE html>
<html lang="en" class="loading">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <title>Hr-system</title>
    <link rel="apple-touch-icon" sizes="60x60" href="../app-assets/img/ico/apple-icon-60.html">
    <link rel="apple-touch-icon" sizes="76x76" href="../app-assets/img/ico/apple-icon-76.html">
    <link rel="apple-touch-icon" sizes="120x120" href="../app-assets/img/ico/apple-icon-120.html">
    <link rel="apple-touch-icon" sizes="152x152" href="../app-assets/img/ico/apple-icon-152.html">
    <link rel="shortcut icon" type="image/png" href="../app-assets/img/logo.png">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900%7CMontserrat:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="../app-assets/fonts/feather/style.min.css">
    <link rel="stylesheet" type="text/css" href="../app-assets/fonts/simple-line-icons/style.css">
    <link rel="stylesheet" type="text/css" href="../app-assets/fonts/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="../app-assets/vendors/css/perfect-scrollbar.min.css">
    <link rel="stylesheet" type="text/css" href="../app-assets/vendors/css/prism.min.css">
    <link rel="stylesheet" type="text/css" href="../app-assets/vendors/css/chartist.min.css">
    <link rel="stylesheet" type="text/css" href="../app-assets/css/app.css">
</head>
<body data-col="2-columns" class=" 2-columns ">

    @section content{
        <div class="main-panel">
            <div class="main-content">
                <div class="content-wrapper">
                    <div class="container-fluid">
                        <!-- Zero configuration table -->
                        <section id="configuration">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="card">


                                        <div class="card-header">
                                            <div class="card-title-wrap bar-success">
                                                <h4 class="card-title">Add user </h4>
                                            </div>
                                        </div>
                                        <div class="card-body">
                                            <div class="px-3">

                                                <form class="form form-horizontal" method="post" enctype="multipart/form-data">

                                                    @Html.HiddenFor(m => m.id_admin)

                                                    <div class="form-body">
                                                        <div class="form-group row">
                                                            <label class="col-md-3 label-control" for="projectinput1">Email: </label>
                                                            <div class="col-md-9">
                                                                @Html.TextBoxFor(m => m.email, new { @class = "form-control" })

                                                            </div>
                                                        </div>
                                                        <div class="form-group row">
                                                            <label class="col-md-3 label-control" for="projectinput1">User Name : </label>
                                                            <div class="col-md-9">
                                                                @Html.TextBoxFor(m => m.user_name, new { @class = "form-control" })
                                                                @Html.ValidationMessageFor(n => n.user_name, null, new { @class = "text-danger" })
                                                            </div>
                                                        </div>
                                                        <div class="form-group row">
                                                            <label class="col-md-3 label-control" for="projectinput1">Password: </label>
                                                            <div class="col-md-9">
                                                                @Html.PasswordFor(m => m.password, new { @class = "form-control" })
                                                                @Html.ValidationMessageFor(n => n.password, null, new { @class = "text-danger" })

                                                            </div>
                                                        </div>
                                                        <div class="form-group row">
                                                            <label class="col-md-3 label-control" for="projectinput7">Group Name : </label>
                                                            <div class="col-md-9">
                                                                @Html.DropDownListFor(n => n.id_group, (SelectList)ViewBag.cat, new { @class = "form-control" })
                                                                @Html.ValidationMessageFor(n => n.id_group, null, new { @class = "text-danger" })


                                                                @*</select>*@
                                                            </div>
                                                        </div>

                                                    </div>
                                                    <input type="submit" value="Save" class="col-12 alert-success" />
                                                    <input type="submit" value="Cancel" class="col-12 btn btn-danger mr-1" />







                                                </form>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </section>

                    </div>
                </div>
            </div>



        </div>

    }
    @section scripts{
        @Scripts.Render("~/bundles/jqueryval")
    }
</body>
</html>

WebApplication1/Views/Admin_/View_users.cshtml
@model List<WebApplication1.Models.Admin>
@{
    ViewBag.Title = "View_users";
    Layout = "~/Views/Shared/_Layout_system.cshtml";
}

@section content{
    <div class="main-panel">
        <div class="main-content">
            <div class="content-wrapper">
                <div class="container-fluid">
                    <!-- Zero configuration table -->
                    <section id="configuration">
                        <div class="row">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-header">
                                        <div class="card-title-wrap bar-success">
                                            <h4 class="card-title">Users Information</h4>
                                        </div>
                                    </div>
                                    <div class="card-body collapse show">
                                        <div class="card-block card-dashboard">
                                            <p class="card-text">
                                                DataTables has most features enabled by default,
                                                so all you need to do to use it with your own ables is to call the construction
                                            </p>

                                                <div class="col-lg-1"></div>
                                                <div class="col-lg-3">
                                                    <button id="addRow" class="btn btn-primary mb-2">
                                                        <i class="ft-plus"></i>&nbsp;
                                                        <a href=@Url.Action("add_new_user","Admin_")>  Add new User</a>
                                                    </button>
                                                </div>
                                            </div>
                                            <table class="table table-striped table-bordered zero-configuration">
                                                <thead>
                                                    <tr>
                                                        <th>Id</th>
                                                        <th>Name</th>
                                                        <th>Edit </th>
                                                        <th>Delete</th>

                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach (var item in Model)
                                                    {


                                                    <tr class="user">
                                                        <td>@item.id_admin</td>
                                                        <td>@item.user_name </td>
                                                        <td>
                                                            <button class="btn btn-success mb-2">
                                                                <a href=@Url.Action("Edit_admin","Admin_",new {id=item.id_admin })>  edit</a>
                                                            </button>
                                                        </td>
                                                        <td>
                                                            <button onclick="return confirm('Are you sure you want to delete this item?')" class="btn btn-danger mb-2">
                                                                <a href=@Url.Action("Delete_admin","Admin_",new {id=item.id_admin })>  delete</a>
                                                            </button>
                                                        </td>


                                                    </tr>

                                                    }                                                                                                                                                                                                                                         </yr>
                                                </tbody>

                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>

                </div>
            </div>
        </div>


    </div>


}

WebApplication1/Views/Admin_/add_new_user.cshtml
@model WebApplication1.Models.Admin
@{
    ViewBag.Title = "add_new_user";
    Layout = "~/Views/Shared/_Layout_system.cshtml";
}

<!DOCTYPE html>
<html lang="en" class="loading">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <title>Hr-system</title>
    <link rel="apple-touch-icon" sizes="60x60" href="../app-assets/img/ico/apple-icon-60.html">
    <link rel="apple-touch-icon" sizes="76x76" href="../app-assets/img/ico/apple-icon-76.html">
    <link rel="apple-touch-icon" sizes="120x120" href="../app-assets/img/ico/apple-icon-120.html">
    <link rel="apple-touch-icon" sizes="152x152" href="../app-assets/img/ico/apple-icon-152.html">
    <link rel="shortcut icon" type="image/png" href="../app-assets/img/logo.png">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900%7CMontserrat:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="../app-assets/fonts/feather/style.min.css">
    <link rel="stylesheet" type="text/css" href="../app-assets/fonts/simple-line-icons/style.css">
    <link rel="stylesheet" type="text/css" href="../app-assets/fonts/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="../app-assets/vendors/css/perfect-scrollbar.min.css">
    <link rel="stylesheet" type="text/css" href="../app-assets/vendors/css/prism.min.css">
    <link rel="stylesheet" type="text/css" href="../app-assets/vendors/css/chartist.min.css">
    <link rel="stylesheet" type="text/css" href="../app-assets/css/app.css">
</head>
<body data-col="2-columns" class=" 2-columns ">

    @section content{
        <div class="main-panel">
            <div class="main-content">
                <div class="content-wrapper">
                    <div class="container-fluid">
                        <!-- Zero configuration table -->
                        <section id="configuration">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="card">


                                        <div class="card-header">
                                            <div class="card-title-wrap bar-success">
                                                <h4 class="card-title">Add user </h4>
                                            </div>
                                        </div>
                                        <div class="card-body">
                                            <div class="px-3">

                                                <form class="form form-horizontal" method="post" enctype="multipart/form-data">

                                                    <div class="form-body">
                                                        <div class="form-group row">
                                                            <label class="col-md-3 label-control" for="projectinput1">Email: </label>
                                                            <div class="col-md-9">
                                                                @Html.TextBoxFor(m => m.email, new { @class = "form-control" })
                                                                @Html.ValidationMessageFor(n => n.email, null, new { @class = "text-danger" })
                                                            </div>
                                                        </div>
                                                        <div class="form-group row">
                                                            <label class="col-md-3 label-control" for="projectinput1">User Name : </label>
                                                            <div class="col-md-9">
                                                                @Html.TextBoxFor(m => m.user_name, new { @class = "form-control" })
                                                                @Html.ValidationMessageFor(n => n.user_name, null, new { @class = "text-danger" })
                                                            </div>
                                                        </div>
                                                        <div class="form-group row">
                                                            <label class="col-md-3 label-control" for="projectinput1">Password: </label>
                                                            <div class="col-md-9">
                                                                @Html.PasswordFor(m => m.password, new { @class = "form-control" })
                                                                @Html.ValidationMessageFor(n => n.password, null, new { @class = "text-danger" })

                                                            </div>
                                                        </div>
                                                        <div class="form-group row">
                                                            <label class="col-md-3 label-control" for="projectinput7">Group Name : </label>
                                                            <div class="col-md-9">
                                                                @Html.DropDownListFor(n => n.id_group, (SelectList)ViewBag.cat, new { @class = "form-control" })
                                                                @Html.ValidationMessageFor(n => n.id_group, null, new { @class = "text-danger" })


                                                                @*</select>*@
                                                            </div>
                                                        </div>

                                                    </div>
                                                    <input type="submit" value="Save" class="col-12 alert-success" />
                                                    <input type="submit" value="Cancel" class="col-12 btn btn-danger mr-1" />







                                                </form>
                                            </div>
                                        </div>
                                        @*@Html.ButtonF ( Model.LabelForCurrentAction(), new { @class = "btn btn-primary btn-large", type = "submit" })*@
                                        @*<div class="form-actions">
                                                <button onclick="location.href = '@Url.Action("adding", "Admin_");'" type="button"
                                                        class="btn btn-danger mr-1">
                                                    <i class="icon-trash"></i> Cancel
                                                </button>
                                                <button type="button" class="btn btn-success">
                                                    <i class="icon-note"></i> Save
                                                </button>
                                            </div>*@
                                    </div>
                                </div>
                            </div>
                        </section>

                    </div>
                </div>
            </div>



        </div>

    }
    @section scripts{
        @Scripts.Render("~/bundles/jqueryval")
    }

</body>
</html>